In [2]:
import pandas as pd
import glob

In [2]:
req_path = "../csv_data_folder/clubs.csv"
req_table_name = req_path.split("/")[-1].split(".")[0]
df = pd.read_csv(req_path)
# df = df.dropna()

In [3]:
df.nunique().to_dict()

{'club_id': 439,
 'club_code': 439,
 'name': 439,
 'domestic_competition_id': 14,
 'total_market_value': 0,
 'squad_size': 31,
 'average_age': 75,
 'foreigners_number': 29,
 'foreigners_percentage': 167,
 'national_team_players': 22,
 'stadium_name': 420,
 'stadium_seats': 402,
 'net_transfer_record': 305,
 'coach_name': 0,
 'last_season': 13,
 'filename': 13,
 'url': 439}

In [4]:
df.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,105,sv-darmstadt-98,SV Darmstadt 98,L1,NaN,27,25.6,13,48.1,1,Merck-Stadion am Böllenfalltor,17810,+€3.05m,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/sv-darmstadt-9...
1,11127,ural-ekaterinburg,Ural Yekaterinburg,RU1,NaN,30,26.5,11,36.7,3,Yekaterinburg Arena,23000,+€880k,NaN,2023,../data/raw/transfermarkt-scraper/2023/clubs.j...,https://www.transfermarkt.co.uk/ural-ekaterinb...
2,114,besiktas-istanbul,Beşiktaş Jimnastik Kulübü,TR1,NaN,30,26.6,15,50.0,8,Beşiktaş Park,42445,€-25.26m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/besiktas-istan...
3,12,as-rom,Associazione Sportiva Roma,IT1,NaN,26,26.3,18,69.2,17,Olimpico di Roma,70634,€-76.90m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
4,148,tottenham-hotspur,Tottenham Hotspur Football Club,GB1,NaN,30,25.5,21,70.0,18,Tottenham Hotspur Stadium,62850,€-120.05m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/tottenham-hots...

In [5]:
df.columns

Index(['club_id', 'club_code', 'name', 'domestic_competition_id',
       'total_market_value', 'squad_size', 'average_age', 'foreigners_number',
       'foreigners_percentage', 'national_team_players', 'stadium_name',
       'stadium_seats', 'net_transfer_record', 'coach_name', 'last_season',
       'filename', 'url'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   club_id                  439 non-null    int64
 1   club_code                439 non-null    object
 2   name                     439 non-null    object
 3   domestic_competition_id  439 non-null    object
 4   total_market_value       0 non-null      float64
 5   squad_size               439 non-null    int64
 6   average_age              401 non-null    float64
 7   foreigners_number        439 non-null    int64
 8   foreigners_percentage    390 non-null    float64
 9   national_team_players    439 non-null    int64
 10  stadium_name             439 non-null    object
 11  stadium_seats            439 non-null    int64
 12  net_transfer_record      439 non-null    object
 13  coach_name               0 non-null      float64
 14  last_season              439 non-null    int64
 15  filename                 439 non-null    object
 16  url                      439 non-null    object
dtypes: float64(4), int64(6), object(7)
memory usage: 58.4+ KB

In [7]:
df['stadium_name'].unique()[:5]

array(['Merck-Stadion am Böllenfalltor', 'Yekaterinburg Arena',
       'Beşiktaş Park', 'Olimpico di Roma', 'Tottenham Hotspur Stadium'],
      dtype=object)

In [8]:
all_paths = list(glob.glob("../csv_data_folder/*.csv"))
column_names_dict = {}
for req_path in all_paths:
    req_file_name = req_path.split("/")[-1].split(".")[0]
    if req_file_name == "game_lineups":
        continue
    else:
        df = pd.read_csv(req_path)
        all_cols = list(df.columns)
        if req_file_name == "game_lineups_cleaned":
            column_names_dict["game_lineups"] = all_cols
        else:
            column_names_dict[req_file_name] = all_cols

In [9]:
column_names_dict

{'competitions': ['competition_id',
  'competition_code',
  'name',
  'sub_type',
  'type',
  'country_id',
  'country_name',
  'domestic_league_code',
  'confederation',
  'url',
  'is_major_national_league'],
 'appearances': ['appearance_id',
  'game_id',
  'player_id',
  'player_club_id',
  'player_current_club_id',
  'date',
  'player_name',
  'competition_id',
  'yellow_cards',
  'red_cards',
  'goals',
  'assists',
  'minutes_played'],
 'player_valuations': ['player_id',
  'date',
  'market_value_in_eur',
  'current_club_id',
  'player_club_domestic_competition_id'],
 'game_lineups': ['game_lineups_id',
  'date',
  'game_id',
  'player_id',
  'club_id',
  'player_name',
  'type',
  'position',
  'number',
  'team_captain'],
 'game_events': ['game_event_id',
  'date',
  'game_id',
  'minute',
  'type',
  'club_id',
  'player_id',
  'description',
  'player_in_id',
  'player_assist_id'],
 'transfers': ['player_id',
  'transfer_date',
  'transfer_season',
  'from_club_id',
  'to_club_id',
  'from_club_name',
  'to_club_name',
  'transfer_fee',
  'market_value_in_eur',
  'player_name'],
 'players': ['player_id',
  'first_name',
  'last_name',
  'name',
  'last_season',
  'current_club_id',
  'player_code',
  'country_of_birth',
  'city_of_birth',
  'country_of_citizenship',
  'date_of_birth',
  'sub_position',
  'position',
  'foot',
  'height_in_cm',
  'contract_expiration_date',
  'agent_name',
  'image_url',
  'url',
  'current_club_domestic_competition_id',
  'current_club_name',
  'market_value_in_eur',
  'highest_market_value_in_eur'],
 'games': ['game_id',
  'competition_id',
  'season',
  'round',
  'date',
  'home_club_id',
  'away_club_id',
  'home_club_goals',
  'away_club_goals',
  'home_club_position',
  'away_club_position',
  'home_club_manager_name',
  'away_club_manager_name',
  'stadium',
  'attendance',
  'referee',
  'url',
  'home_club_formation',
  'away_club_formation',
  'home_club_name',
  'away_club_name',
  'aggregate',
  'competition_type'],
 'club_games': ['game_id',
  'club_id',
  'own_goals',
  'own_position',
  'own_manager_name',
  'opponent_id',
  'opponent_goals',
  'opponent_position',
  'opponent_manager_name',
  'hosting',
  'is_win'],
 'clubs': ['club_id',
  'club_code',
  'name',
  'domestic_competition_id',
  'total_market_value',
  'squad_size',
  'average_age',
  'foreigners_number',
  'foreigners_percentage',
  'national_team_players',
  'stadium_name',
  'stadium_seats',
  'net_transfer_record',
  'coach_name',
  'last_season',
  'filename',
  'url']}

### Get unique values in game_lineups data

In [10]:
df = pd.read_csv("../csv_data_folder/game_lineups_cleaned.csv")
print(df.shape)
df.head()

(2191911, 10)

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

In [13]:
for req_col in ['type', 'position']:
    req_vals = df[req_col].unique().tolist()
    req_stmt = f"The unique values in {req_col} column in game_lineups table are: {req_vals}"
    print(req_stmt)

The unique values in type column in game_lineups table are: ['substitutes', 'starting_lineup']
The unique values in position column in game_lineups table are: ['Defensive Midfield', 'Centre-Back', 'Left Winger', 'Left-Back', 'Right Winger', 'Goalkeeper', 'Attacking Midfield', 'Centre-Forward', 'Central Midfield', 'Right-Back', 'Right Midfield', 'Left Midfield', 'Second Striker', 'Defender', 'midfield', 'Attack', 'Sweeper', nan]

In [3]:
players_data = pd.read_csv("../csv_data_folder/players.csv")
print(players_data.shape)
players_data.head()

(32601, 23)

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [4]:
players_data.columns

Index(['player_id', 'first_name', 'last_name', 'name', 'last_season',
       'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name',
       'image_url', 'url', 'current_club_domestic_competition_id',
       'current_club_name', 'market_value_in_eur',
       'highest_market_value_in_eur'],
      dtype='object')

In [15]:
print(f"current_club_name: {players_data['current_club_name'].unique()[:15].tolist()}")

current_club_name: ['Società Sportiva Lazio S.p.A.', 'Borussia Dortmund', 'Panthessalonikios Athlitikos Omilos Konstantinoupoliton', 'Juventus Football Club', 'FC Bayern München', 'Eskisehirspor', 'FC Schalke 04', 'Arsenal Football Club', 'Verein für Bewegungsspiele Stuttgart 1893', 'Málaga CF', 'FC Vestsjaelland', 'Levante UD', 'Kasımpaşa Spor Kulübü', 'Galatasaray Spor Kulübü', 'Eintracht Frankfurt Fußball AG']